In [3]:
asp155_str = """
N	41.760, 37.709, 31.860	-0.31
H	41.809, 38.049, 30.920	0.31
CA	40.360, 37.449, 32.360	0
CB	39.409, 37.689, 31.220	0
CG	37.980, 37.899, 31.790	0.27
OD1	37.640, 37.449, 32.860	-0.635
OD2	37.260, 38.679, 31.090	-0.635
C	40.210, 36.029, 32.910	0.45
O	39.810, 35.829, 34.070	-0.45
"""

cmyh_str = """
N07	37.039, 28.549, 28.060	-0.553
C06	37.299, 29.489, 28.680	0.493
C05	37.109, 30.739, 29.370	-0.335
C04	37.409, 30.789, 30.760	-0.132
HC04	37.989, 29.959, 31.170	0.17
C03	37.189, 31.969, 31.480	0.18
O02	37.109, 32.089, 32.870	-0.197
C01	37.439, 30.929, 33.700	-0.15
H011	38.439, 30.519, 33.510	0.11
H012	37.389, 31.219, 34.750	0.11
H013	36.719, 30.129, 33.580	0.11
C12	36.819, 33.149, 30.750	0.021
C11	36.639, 33.079, 29.430	-0.315
HC11	36.249, 33.919, 28.850	0.181
C08	36.679, 31.879, 28.690	0.43
O09	36.659, 31.839, 27.330	-0.325
C10	36.079, 32.839, 26.460	-0.062
H101	36.449, 33.859, 26.590	0.097
H102	36.309, 32.619, 25.420	0.097
H103	34.989, 32.899, 26.380	0.097
C13	36.829, 34.499, 31.380	-0.138
H131	37.269, 35.209, 30.690	0.093
H132	37.509, 34.559, 32.230	0.093
C14	35.419, 34.879, 31.720	-0.045
H141	35.239, 34.509, 32.730	0.106
H142	34.709, 34.470, 30.990	0.106
N15	35.139, 36.419, 31.770	-0.118
H151	34.939, 36.699, 30.800	0.304
H152	36.060, 36.859, 31.950	0.304
C16	34.110, 37.030, 32.750	-0.224
H161	34.660, 37.620, 33.480	0.164
H162	33.470, 37.710, 32.180	0.164
C17	33.330, 35.990, 33.580	0.049
C22	33.210, 36.140, 34.980	0.292
O23	34.330, 36.570, 35.640	-0.571
HO23	35.160, 36.369, 35.170	0.471
C21	32.220, 35.500, 35.620	-0.29
HC21	32.110, 35.770, 36.670	0.174
C20	31.240, 34.760, 34.970	-0.07
HC20	30.320, 34.460, 35.470	0.146
C19	31.310, 34.620, 33.620	-0.198
HC19	30.429, 34.350, 33.030	0.155
C18	32.400, 35.160, 32.920	-0.139
HC18	32.629, 34.890, 31.890	0.145
"""
from io import StringIO
import pandas as pd
headers = ["atom", "xyz", "charge"]
asp155_io = StringIO(asp155_str)
cmyh_io = StringIO(cmyh_str)

asp155_df = pd.read_csv(asp155_io, sep="\t", names = headers)
cmyh_df = pd.read_csv(cmyh_io, sep="\t", names = headers)

In [15]:
import numpy as np
asp155_points = np.array([np.array(x.split(","), dtype=float) for x in asp155_df["xyz"]])
cmyh_points = np.array([np.array(x.split(","), dtype=float) for x in cmyh_df["xyz"]])

In [17]:
asp155_points

array([[4.176 , 3.7709, 3.186 ],
       [4.1809, 3.8049, 3.092 ],
       [4.036 , 3.7449, 3.236 ],
       [3.9409, 3.7689, 3.122 ],
       [3.798 , 3.7899, 3.179 ],
       [3.764 , 3.7449, 3.286 ],
       [3.726 , 3.8679, 3.109 ],
       [4.021 , 3.6029, 3.291 ],
       [3.981 , 3.5829, 3.407 ]])

In [19]:
asp155_df["xyz"] = asp155_points
cmyh_df["xyz"] = cmyh_points

In [21]:
cmyh_df.iter_tuple

    atom                         xyz  charge
0    N07  [37.039,  28.549,  28.060]  -0.553
1    C06  [37.299,  29.489,  28.680]   0.493
2    C05  [37.109,  30.739,  29.370]  -0.335
3    C04  [37.409,  30.789,  30.760]  -0.132
4   HC04  [37.989,  29.959,  31.170]   0.170
5    C03  [37.189,  31.969,  31.480]   0.180
6    O02  [37.109,  32.089,  32.870]  -0.197
7    C01  [37.439,  30.929,  33.700]  -0.150
8   H011  [38.439,  30.519,  33.510]   0.110
9   H012  [37.389,  31.219,  34.750]   0.110
10  H013  [36.719,  30.129,  33.580]   0.110
11   C12  [36.819,  33.149,  30.750]   0.021
12   C11  [36.639,  33.079,  29.430]  -0.315
13  HC11  [36.249,  33.919,  28.850]   0.181
14   C08  [36.679,  31.879,  28.690]   0.430
15   O09  [36.659,  31.839,  27.330]  -0.325
16   C10  [36.079,  32.839,  26.460]  -0.062
17  H101  [36.449,  33.859,  26.590]   0.097
18  H102  [36.309,  32.619,  25.420]   0.097
19  H103  [34.989,  32.899,  26.380]   0.097
20   C13  [36.829,  34.499,  31.380]  -0.138
21  H131  [37.269,  35.209,  30.690]   0.093
22  H132  [37.509,  34.559,  32.230]   0.093
23   C14  [35.419,  34.879,  31.720]  -0.045
24  H141  [35.239,  34.509,  32.730]   0.106
25  H142  [34.709,  34.470,  30.990]   0.106
26   N15  [35.139,  36.419,  31.770]  -0.118
27  H151  [34.939,  36.699,  30.800]   0.304
28  H152  [36.060,  36.859,  31.950]   0.304
29   C16  [34.110,  37.030,  32.750]  -0.224
30  H161  [34.660,  37.620,  33.480]   0.164
31  H162  [33.470,  37.710,  32.180]   0.164
32   C17  [33.330,  35.990,  33.580]   0.049
33   C22  [33.210,  36.140,  34.980]   0.292
34   O23  [34.330,  36.570,  35.640]  -0.571
35  HO23  [35.160,  36.369,  35.170]   0.471
36   C21  [32.220,  35.500,  35.620]  -0.290
37  HC21  [32.110,  35.770,  36.670]   0.174
38   C20  [31.240,  34.760,  34.970]  -0.070
39  HC20  [30.320,  34.460,  35.470]   0.146
40   C19  [31.310,  34.620,  33.620]  -0.198
41  HC19  [30.429,  34.350,  33.030]   0.155
42   C18  [32.400,  35.160,  32.920]  -0.139
43  HC18  [32.629,  34.890,  31.890]   0.145